import builtins from "builtin-modules";
import esbuild from "esbuild";
import process from "process";

const prod = process.argv[2] === "production";

const banner = `/*
THIS FILE IS GENERATED BY ESBUILD — DO NOT EDIT main.js DIRECTLY.
*/
`;

const ctx = await esbuild.context({
	banner: { js: banner },
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/state",
		"@codemirror/view",
		"@codemirror/language",
		"@lezer/common",
		...builtins,
	],
	platform: "browser",
	format: "cjs",
	target: "es2022",
	loader: {
		".wasm": "binary",
	},
	outfile: "main.js",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	logLevel: "info",
});

if (prod) {
	await ctx.rebuild();
	await ctx.dispose();
	process.exit(0);
}

await ctx.watch();
